kind: Service
apiVersion: v1
metadata:
  name:  db
  label:
    name: db-service
    app: demo-voting-app
spec:
  selector:
      name: postgres-pod
      app: demo-voting-app
  type:  ClusterIP
  ports:
  - port:  5432
    targetPort:  5432