kind: Service
apiVersion: v1
metadata:
  name:  redis
  label:
    name: redis
    app: demo-voting-app
spec:
  selector:
    name: redis-pod
    app: demo-voting-app
  type:  ClusterIP
  ports:
  - port:  6379
    targetPort:  6379