kind: Service
apiVersion: v1
metadata:
  name:  voting-service
  label:
    name: voting-service
    app: demo-voting-app
spec:
  selector:
      name: voting-app-pod
      app: demo-voting-app
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80